### ISSUE TITLE
Unable to connect device 

### ISSUE THREAD

**Issue by Madhav131** [tulparyazilim/tp-react-native-bluetooth-printer#11]
some device are get this error " unable to connect device " 
Android version : 12 
miui version :13 
how to get solve  this error plaese any help us

**Comment by Rehankhalil462** [comment]
> some device are get this error " unable to connect device " Android version : 12 miui version :13 how to get solve this error plaese any help us

@Madhav131  check if you have allowed the Bluetooth permission to the application or not? and also while connecting , it opens a prompt to pair with the respective device, if you would cancel to pair, then you would not be able to connect with the device.

**Comment by Madhav131** [comment]
@Rehankhalil462  i wii check Bluetooth permission to the application done and connecting device, but same error show it you have any idea for this error?

**Comment by Philip970** [comment]
@Rehankhalil462 I have the same problem, I granted the permissions. Did you solve it?

**Comment by Rehankhalil462** [comment]
> @Rehankhalil462 I have the same problem, I granted the permissions. Did you solve it?

@Philip970, can you please piece of code where you are requesting permissions and using this library function to discover the devices?

**Comment by Philip970** [comment]
@Rehankhalil462 

Here is the code to scan the devices

`const scanBluetoothDevice = async () => {
    setLoading(true);
    try {
      const request = await requestMultiple([
        PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
        PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
        PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      ]);

      if (
        request["android.permission.ACCESS_FINE_LOCATION"] === RESULTS.GRANTED
      ) {
        scanDevices();
        setLoading(false);
      } else {
        setLoading(false);
      }
    } catch (err) {
      setLoading(false);
    }
  };`

`const scanDevices = useCallback(() => {
    setLoading(true);
    BluetoothManager.scanDevices().then(
      (s) => {
        // const pairedDevices = s.paired;
        var found = s.found;
        try {
          found = JSON.parse(found);
        } catch (e) {
          //ignore
        }
        var fds = foundDs;
        if (found && found.length) {
          fds = found;
        }
        setFoundDs(fds);
        setLoading(false);
      },
      (er) => {
        setLoading(false);
        // ignore
      },
    );
  }, [foundDs]);`

Here is the code to connect

`const connect = (row) => {
    setLoading(true);
    BluetoothManager.connect(row.address).then(
      (s) => {
        setLoading(false);
        setBoundAddress(row.address);
        setName(row.name || "UNKNOWN");
      },
      (e) => {
        setLoading(false);
        alert(e); // Here it shows error " unable to connect device "
      },
    );
  };`

**Comment by Rehankhalil462** [comment]
> @Rehankhalil462 
> 
> Here is the code to scan the devices
> 
> `const scanBluetoothDevice = async () => {
>     setLoading(true);
>     try {
>       const request = await requestMultiple([
>         PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
>         PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
>         PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
>       ]);
> 
>       if (
>         request["android.permission.ACCESS_FINE_LOCATION"] === RESULTS.GRANTED
>       ) {
>         scanDevices();
>         setLoading(false);
>       } else {
>         setLoading(false);
>       }
>     } catch (err) {
>       setLoading(false);
>     }
>   };`
> 
> `const scanDevices = useCallback(() => {
>     setLoading(true);
>     BluetoothManager.scanDevices().then(
>       (s) => {
>         // const pairedDevices = s.paired;
>         var found = s.found;
>         try {
>           found = JSON.parse(found);
>         } catch (e) {
>           //ignore
>         }
>         var fds = foundDs;
>         if (found && found.length) {
>           fds = found;
>         }
>         setFoundDs(fds);
>         setLoading(false);
>       },
>       (er) => {
>         setLoading(false);
>         // ignore
>       },
>     );
>   }, [foundDs]);`
> 
> Here is the code to connect
> 
> `const connect = (row) => {
>     setLoading(true);
>     BluetoothManager.connect(row.address).then(
>       (s) => {
>         setLoading(false);
>         setBoundAddress(row.address);
>         setName(row.name || "UNKNOWN");
>       },
>       (e) => {
>         setLoading(false);
>         alert(e); // Here it shows error " unable to connect device "
>       },
>     );
>   };`
> 
> Any help would be appreciated thank you


This looks fine to me. 
Can you please tell me which OS you are working on?

**Comment by Philip970** [comment]
@Rehankhalil462 It works, I just have to retry the connection several times. But I have an issue with the QR Code

**Comment by Philip970** [comment]
I have the error: BluetoothEscposPrinter.printQRCode got 5 arguments, expected 6

`
BluetoothEscposPrinter.printQRCode(
              "https://hsd.co.id",
              280,
              BluetoothEscposPrinter.ERROR_CORRECTION.L,
            );
`

**Comment by Philip970** [comment]
I have the error: BluetoothEscposPrinter.printQRCode got 5 arguments, expected 6

`
BluetoothEscposPrinter.printQRCode(
              "https://hsd.co.id",
              280,
              BluetoothEscposPrinter.ERROR_CORRECTION.L,
            );
`

**Comment by Rehankhalil462** [comment]
@Philip970  
try this
```javascript
BluetoothEscposPrinter.printQRCode(
        "https://hsd.co.id",
        280,
        BluetoothEscposPrinter.ERROR_CORRECTION.L,
        0
      );
```

Note : Make sure you are connected to your printer device using connect method . 
Following code to connect with your device for your reference.
```javascript
await BluetoothManager.connect("your_bluetooth_device_address")
```

**Comment by Philip970** [comment]
@Rehankhalil462 It works ! Thanks you for your Help !

**Comment by Rehankhalil462** [comment]
@Philip970 You are welcome.  I am glad that it solved your issue.

**Comment by DARPANMANEK** [comment]
can't connect to device with this library can anyone help?

**Comment by Madhav131** [comment]
@DARPANMANEK check if you have allowed the Bluetooth permission to the application or not? and also while connecting

**Comment by DARPANMANEK** [comment]
Yeah i did

**Comment by DARPANMANEK** [comment]
But I can't connect

**Comment by Madhav131** [comment]
@DARPANMANEK which is your Android version?

**Comment by DARPANMANEK** [comment]
Android 12

**Comment by DARPANMANEK** [comment]
here, this is my code 

const connect = row => {
    setLoading(true);
    BluetoothManager.connect(row).then(
      s => {
        setLoading(false);
        setBoundAddress(row);
        // setName(row.name || 'UNKNOWN');
      },
      e => {
        setLoading(false);
        alert(e);
      },
    );
  };

**Comment by Rehankhalil462** [comment]
> here, this is my code
> 
> const connect = row => { setLoading(true); BluetoothManager.connect(row).then( s => { setLoading(false); setBoundAddress(row); // setName(row.name || 'UNKNOWN'); }, e => { setLoading(false); alert(e); }, ); };

@DARPANMANEK 
Change `BluetoothManager.connect(row)` to `BluetoothManager.connect(row.address)`.
And 
Change `setBoundAddress(row)` to `setBoundAddress(row.address)`.

**Comment by DARPANMANEK** [comment]
@Rehankhalil462 i already store address seprately in usestate

**Comment by Rehankhalil462** [comment]
@DARPANMANEK  which error are you getting then?

**Comment by DARPANMANEK** [comment]
@Rehankhalil462 
I got "Unable To Connect Device" Device

**Comment by DARPANMANEK** [comment]
@Rehankhalil462 any solution?

**Comment by Rehankhalil462** [comment]
@DARPANMANEK  I can not tell you the solution without get to know about the environment , code sample, etc. Please create a reproducible demo and then share with me. I will then check and let you know.

**Comment by DARPANMANEK** [comment]
ok
