### ISSUE TITLE
IOS Build Error 

### ISSUE THREAD

**Issue by Rehankhalil462** [tulparyazilim/tp-react-native-bluetooth-printer#15]
Getting this error on building for IOS
```javascript
❌  duplicate symbol '_A' in
┌─ libRNBluetoothEscposPrinter.a(RNBluetoothEscposPrinter.o)
└─ libepos2.a(AccesscodeEngine.o)
❌  ld: 1 duplicate symbol for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am using your library for Scanning bluetooth devices and using this  https://github.com/tr3v3r/react-native-esc-pos-printer for printing receipts. 

Working fine on Android without any build error.

 IOS Build Environment 

```javascript
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.210.0                 |
| sdk         | iPhoneOS16.0.sdk        |
+-------------+-------------------------+
```

@khairul169 @omerakyol @tulparyazilim @lufke

any help?

**Comment by lufke** [comment]
I don't use iOS , so I can't help

**Comment by Rehankhalil462** [comment]
Fixed this issue in this PR : https://github.com/tulparyazilim/tp-react-native-bluetooth-printer/pull/16.
