### ISSUE TITLE
After install the package when i try to run the project i am getting this error from this package  "TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {     FORWARD: 0,     BACKWARD: 1   }')"

### ISSUE THREAD

**Issue by Tamilarasan-ThiDiff** [tulparyazilim/tp-react-native-bluetooth-printer#17]
TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = {
    FORWARD: 0,
    BACKWARD: 1
  }')
![Screenshot 2023-03-20 at 7 41 31 PM](https://user-images.githubusercontent.com/90826888/226366169-30026990-0b32-4123-be57-ca19927f31ee.jpg)

**Comment by DukazzCruz** [comment]
show me your option code
and the module import

**Comment by Tamilarasan-ThiDiff** [comment]
import {
  BluetoothManager,
  BluetoothEscposPrinter,
  BluetoothTscPrinter,
} from "tp-react-native-bluetooth-printer";

This is my import in my project

**Comment by FreddyJuniorCampos** [comment]
npm is not updated, Try this:

npm install https://github.com/tulparyazilim/tp-react-native-bluetooth-printer.git --save

**Comment by Tamilarasan-ThiDiff** [comment]
Thank for reply 😊, i have fixed this issue , The problem is my environment native modules not importing correctly because i have used Expo-go app so instead of that i am using android studio native modules are importing and it is working without any issue
