### ISSUE TITLE
Couldn't print more than two times

### ISSUE THREAD

**Issue by Rooban19** [tulparyazilim/tp-react-native-bluetooth-printer#19]
Eventhough  I configured the package properly, I couldn't able to take print more than two times. Seems like the connection is lost. How to re-establish the connection whenever the connection getting lost. I attached the code below
 
`   const _connectPrinter = ( printer ) => {
    BluetoothManager.connect( "66:32:87:DF:B5:2A" ).then( ( s ) => {
    console.log( s );
    }
).catch( ( e ) => {
console.log( "Not Connected", e );
} );
};

useEffect( () => {
DeviceEventEmitter.addListener( BluetoothManager.EVENT_DEVICE_ALREADY_PAIRED, ( rsp ) => {
console.log( "EVENT_DEVICE_ALREADY_PAIRED", rsp );
}
);
DeviceEventEmitter.addListener( BluetoothManager.EVENT_DEVICE_FOUND, ( rsp ) => {
console.log( "EVENT_DEVICE_FOUND", rsp );
}
);
DeviceEventEmitter.addListener( BluetoothManager.EVENT_CONNECTION_LOST, () => {
console.log( "EVENT_CONNECTION_LOST" );
// _connectPrinter();
}
);
}, [] );

const printTextTest = async () => {
await BluetoothEscposPrinter.printerInit();
await BluetoothEscposPrinter.printerAlign( BluetoothEscposPrinter.ALIGN.CENTER );
await BluetoothEscposPrinter.setBold( 0 );
await BluetoothEscposPrinter.printText( "MY LOVED TITLE\n\r", {
encoding: "GBK",
codepage: 0,
widthtimes: 3,
heigthtimes: 3,
fonttype: 1,
} );
await BluetoothEscposPrinter.setBold( 0 );
await BluetoothEscposPrinter.printText( "SECOND TITLE\n\r", {
encoding: "GBK",
codepage: 0,
widthtimes: 0,
heigthtimes: 0,
fonttype: 1,
} );
await BluetoothEscposPrinter.printerAlign( BluetoothEscposPrinter.ALIGN.CENTER );
await BluetoothEscposPrinter.printText( "Label：Value\n\r", {} );
await BluetoothEscposPrinter.printText( "Code：xsd201909210000001\n\r", {} );
await BluetoothEscposPrinter.printText(
"Date：" + "12-12-12" + "\n\r",
{}
);
await BluetoothEscposPrinter.printText( "Number：18664896621\n\r", {} );
await BluetoothEscposPrinter.printText(
"--------------------------------\n\r",
{}
);
await BluetoothEscposPrinter.printText( "Amount：64000.00\n\r", {} );
await BluetoothEscposPrinter.printText( "Tax：0.00\n\r", {} );
await BluetoothEscposPrinter.printText( "Total：64000.00\n\r", {} );
 await BluetoothEscposPrinter.printText(
        "--------------------------------\n\r",
        {}
    );
    await BluetoothEscposPrinter.printerAlign( BluetoothEscposPrinter.ALIGN.CENTER );
    await BluetoothEscposPrinter.printText( "Thanks for payment\n\r\n\r\n\r", {} );
    await BluetoothEscposPrinter.printerAlign( BluetoothEscposPrinter.ALIGN.LEFT );

};
<Button title="Connect" onPress={ _connectPrinter } />
<Button title="Print" onPress={ printTextTest } />`

**Comment by Tamilarasan-ThiDiff** [comment]
You can use for loop for printing multiple copies inside the for loop you can call the print function it will work

**Comment by Rooban19** [comment]
But the printer gets disconnected once I printed .... So, I couldn't able
to print next time
