### ISSUE TITLE
Types of printer´s encoding and codepage

### ISSUE THREAD

**Issue by tradesystem** [tulparyazilim/tp-react-native-bluetooth-printer#2]
Hi,

First of all, sorry for my awful´s English :( 

I´m trying to use this library, and I encounter a issue in the development of my app. I need to print some characters like 'ã', 'â', however this don't work. Which are the codepage and encoding available in this lib? And where I found these codes? Example, in the documentation, you said the number 13 are the Turkish codepage. How can I know the others codepages available?

**Comment by tulparyazilim** [comment]
@tradesystem Actually codepages are related to bluetooth printer so you can reveal it after you make a self test of printer. Also you can find here so many encoding https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html
