### ISSUE TITLE
In this print package i am trying to print the indian Rupee symbol (₹) with amount  but it is not printing it is printing other symbol (?)

### ISSUE THREAD

**Issue by Tamilarasan-ThiDiff** [tulparyazilim/tp-react-native-bluetooth-printer#21]
Hii ...

In this printer i need to print the Indian currency symbol (₹) , when i add the symbol in
**await BluetoothEscposPrinter.printText("₹" ,{});**
it is not printing the currency symbol , it is printing the some other symbol

if you have any thoughts about this please share me

Note:   tp-react-native-bluetooth-printer - 1.3.5. this version package i am using

Thanks in advance

i have attached screenshot for your reference , In this screenshot first symbol is rupee symbol it is printing like this But other symbols are printing correctly

![IMG_20230428_191311](https://user-images.githubusercontent.com/90826888/235184343-c88bb961-5353-49d6-80fe-21908ac07814.jpg)

**Comment by omerakyol** [comment]
@Tamilarasan-ThiDiff You can try with different encoding and codepage parameters.

**Comment by joypatel04** [comment]
@Tamilarasan-ThiDiff Can you please tell me which printer are you using? I am trying to understand on which printer this modules supports?

I am looking to integrate bluethooth thermal label printer and not sure which one to buy.
