### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by kruyvanna** [tulparyazilim/tp-react-native-bluetooth-printer#22]
I got A function declaration without a prototype is deprecated in all versions of C error

<img width="1013" alt="Screenshot 2023-08-04 at 12 27 06 PM" src="https://github.com/tulparyazilim/tp-react-native-bluetooth-printer/assets/1171793/fecab2b2-0d19-4c1e-8645-83d7036a7665">

After fix suggestion by Xcode, I got another error 
Expression does not compute the number of elements in this array; element type is 'const unichar' (aka 'const unsigned short'), not 'char'

<img width="1013" alt="Screenshot 2023-08-04 at 12 33 09 PM" src="https://github.com/tulparyazilim/tp-react-native-bluetooth-printer/assets/1171793/1bf97304-8860-41b5-b1d5-98bc27f0741e">

My Xcode version is: 14.3.1 
Thank you

**Comment by omerakyol** [comment]
@kruyvanna Actually we don't get any these errors on our react native projects in xcode.

**Comment by joypatel04** [comment]
@kruyvanna You able to solve this issue? It seems when a project is an expo project then this issue occurs.
