### ISSUE TITLE
response from printLabel is null

### ISSUE THREAD

**Issue by ghozihumama** [tulparyazilim/tp-react-native-bluetooth-printer#25]
response from connect is name of the printer but when call printLabel the response is null and the printer device doing nothing. 

  async print(options) {
    BluetoothTscPrinter.printText(options).then(
      res => {
        console.log(`success`, res);
      },
      err => {
        console.log(`err`, err);
      },
    );
  }
  
  
  console.log(`success`, res);
  success, null

**Comment by omerakyol** [comment]
@ghozihumama Is your printer supports TSC features?
