### ISSUE TITLE
IOS: TypeError: null is not an object (evaluating 'BluetoothTscPrinter.DIRECTION = { FORWARD: 0, BACKWARD: 1 }')

### ISSUE THREAD

**Issue by studiozocaro** [tulparyazilim/tp-react-native-bluetooth-printer#3]
In main fork fix error,
please update this fork
https://github.com/januslo/react-native-bluetooth-escpos-printer/pull/76/files#diff-75e8fa81df55e5ab71cf0150c5c5dcca0f0a49180e18da250d5e46654a28c438

**Comment by NgocLe1001** [comment]
any one helps please!!!!
