### ISSUE TITLE
This library is not working for  Andriod 12 + version

### ISSUE THREAD

**Issue by Madhav131** [tulparyazilim/tp-react-native-bluetooth-printer#8]
this library not woking for  for Andriod 12 + version , all support  configure file and permission any one idea please help us

**Comment by khairul169** [comment]
try pulling PR #7 locally, this should fix android 12 build

**Comment by tulparyazilim** [comment]
> this library not woking for for Andriod 12 + version , all support configure file and permission any one idea please help us

#7 PR merged. Please try again.
